-- Catálogo editorial público; perfis e favoritos pertencem ao usuário autenticado.
create extension if not exists "pgcrypto";
create table public.beaches (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, neighborhood text not null, category text not null, latitude double precision not null, longitude double precision not null, description text not null, history text, best_time text, best_season text, sand_type text, water_color text, wave_type text, is_published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.beach_images (id uuid primary key default gen_random_uuid(), beach_id uuid not null references public.beaches(id) on delete cascade, storage_path text not null unique, alt_text text not null, position smallint not null default 0, attribution text not null, license_url text not null, created_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_path text, created_at timestamptz not null default now());
create table public.favorites (user_id uuid not null references auth.users(id) on delete cascade, beach_id uuid not null references public.beaches(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id, beach_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create index favorites_user_id_idx on public.favorites(user_id); create index beach_images_beach_id_idx on public.beach_images(beach_id); create index notifications_user_id_idx on public.notifications(user_id);
alter table public.beaches enable row level security; alter table public.beach_images enable row level security; alter table public.profiles enable row level security; alter table public.favorites enable row level security; alter table public.notifications enable row level security;
create policy "published beaches are public" on public.beaches for select to anon, authenticated using (is_published = true);
create policy "published beach images are public" on public.beach_images for select to anon, authenticated using (exists (select 1 from public.beaches b where b.id = beach_id and b.is_published = true));
create policy "profile owner can read" on public.profiles for select to authenticated using ((select auth.uid())=id); create policy "profile owner can insert" on public.profiles for insert to authenticated with check ((select auth.uid())=id); create policy "profile owner can update" on public.profiles for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
create policy "favorites owner manages" on public.favorites for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "notification owner reads" on public.notifications for select to authenticated using ((select auth.uid())=user_id); create policy "notification owner updates" on public.notifications for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
-- Create private bucket 'beach-gallery' in the dashboard; publish only image derivatives with license metadata.
create table public.plans (code text primary key, name text not null, price_cents integer not null check(price_cents>=0), currency text not null default 'BRL', active boolean not null default true);
insert into public.plans(code,name,price_cents) values ('premium_monthly','Premium mensal',2990);
create table public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete restrict, plan_code text not null references public.plans(code), provider text not null default 'cakto', provider_customer_id text unique, provider_subscription_id text unique, status text not null check(status in ('active','past_due','canceled','pending','expired')), current_period_start timestamptz, current_period_end timestamptz, next_charge_at timestamptz, cancel_at_period_end boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.payment_events (id uuid primary key default gen_random_uuid(), provider_event_id text unique not null, subscription_id uuid references public.subscriptions(id) on delete set null, event_type text not null, payload jsonb not null, received_at timestamptz not null default now());
create index subscriptions_user_id_idx on public.subscriptions(user_id); create index subscriptions_status_idx on public.subscriptions(status);
alter table public.plans enable row level security; alter table public.subscriptions enable row level security; alter table public.payment_events enable row level security;
create policy "plans are public" on public.plans for select to anon,authenticated using(active); create policy "subscriber reads own subscription" on public.subscriptions for select to authenticated using((select auth.uid())=user_id);
grant select on public.plans to anon,authenticated; grant select on public.subscriptions to authenticated;
